### ISSUE TITLE
Research examples of technological solutions to promote sustainable campus life

### ISSUE THREAD

**Issue by TheSloanRanger** [Nintails-TF/agile-smart-campus#11]
As a member of the campus community, I want renewable energy sources and eco-friendly infrastructure to promote a sustainable campus life.

**Comment by Lucca-C** [comment]
https://blueandgreentomorrow.com/features/eco-conscious-campuses-students-drive-sustainability-initiatives/
University of California, Davis: This university has made significant strides in sustainability, aiming to become carbon neutral by 2025. They've implemented various sustainable practices, including a comprehensive bike-sharing program, energy-efficient buildings, and a zero-waste commitment. These efforts demonstrate the university's dedication to reducing its carbon footprint and promoting eco-friendly campus living​​.

https://e360.yale.edu/features/on_college_campuses_progress_on_renewable_energy
Colorado State University: Colorado State has made considerable progress in renewable energy adoption. Starting in 2009, the university installed 6,600 kilowatts of solar electricity across its campuses. This installation includes a significant 5.3-megawatt ground-mounted system, demonstrating the university's commitment to renewable energy. While the university doesn't own all its solar systems, the smaller arrays it does own contribute 3 to 4 percent of the campus's power. Colorado State's efforts highlight the potential for educational institutions to significantly invest in renewable energy sources​​.

https://www.nrdc.org/bio/lara-ettenson/how-college-campuses-can-lead-fighting-climate-change
Cornell University: Cornell University developed an award-winning Climate Action Plan in 2009, aiming to cut net carbon emissions to zero by 2035. Since 2008, the university has reduced its gross emissions by more than 30 percent. Key strategies include using renewable sources for electricity, replacing traditional chillers with a deep lake water cooling system, and phasing out on-site coal combustion. Cornell's commitment is evident not only in infrastructure but also in the student lifestyle, promoting water conservation and other sustainable practices​​.
