### ISSUE TITLE
Research examples of technological solutions to monitor resource consumption and environmental conditions in campus

### ISSUE THREAD

**Issue by TheSloanRanger** [Nintails-TF/agile-smart-campus#13]
As a Staff Member, I need smart sensors to monitor resource consumption and environmental conditions, to ensure a sustainable campus environment.

Definition of done: 2 examples of technological solutions to monitor resource consumption and environmental conditions in campus

**Comment by lewissimmonds** [comment]
User Story: As a Staff Member, I need smart sensors to monitor resource consumption and environmental conditions to ensure a sustainable campus environment.

Must: The integration of smart sensors is essential for monitoring and managing resource consumption and environmental conditions on campus, crucial for sustainability and operational efficiency.

High Value: This project provides significant benefits in terms of enhanced resource management and environmental stewardship. It leads to improved decision-making, operational efficiency, and campus sustainability.

Low Risk: The deployment of smart sensors is a low-risk venture due to established technologies and precedents in various universities.

Examples:

 - Carnegie Mellon University: The university has established a sophisticated energy management system across nine buildings, utilizing hundreds of sensors. This system tracks various parameters like heating, cooling, ventilation, and lighting. The integration of this data through predictive analytics and real-time dashboards allows for more efficient energy usage, leading to substantial cost savings and reduced environmental impact. https://campustechnology.com/Articles/2014/10/09/Carnegie-Mellon-Manages-Energy-Usage-with-Predictive-Analytics.aspx

    University of California, Irvine: Their Smart Labs program is a comprehensive initiative focusing on energy efficiency in research laboratories. It includes a series of energy-efficient measures and monitoring systems, tailored to reduce energy consumption in these high-demand settings. The program is part of a broader commitment to sustainability and efficient resource use on campus. https://smartlabs.i2sl.org/cs-uci-sla.html

    Stanford University: Stanford's approach involves a wide-ranging environmental monitoring system. This system tracks key metrics like energy use, water consumption, and waste production. The data collected is used to improve the campus's sustainability practices, aiming to create a healthier and more environmentally responsible community. https://sustainable.stanford.edu/
