### ISSUE TITLE
Research about real-time notification systems

### ISSUE THREAD

**Issue by AmSmef** [Nintails-TF/agile-smart-campus#14]
As a student, I want to receive real-time notifications about class schedule changes, room assignments, and campus events on my smartphone to stay informed and plan my day effectively. 

DoD (definition of done) - 4 solutions

**Comment by KyleTait01** [comment]
Many universities have dedicated apps for receiving real-time notifications for class schedule changes/room assignments/campus events. Lecturers can use the app to update students on any of these issues when they arise. These apps often allow students to customise their notifications preferences to suit their needs.

Universities may also make use of calendar integration in order to integrate class schedules and campus events with popular calendar apps such as Google Calendar or Apple Calendar. This allows students to receive real-time notifications on their phone about any changes or additions to schedules.

SMS alerts may be used to notify students on these issues - this allows students to receive important notifications about any changes even if they are not using a specific app.

Universities may opt to use email in order to notify students about any important changes. Students can enable themselves to receive push notifications from email and this would allow them to be updated in real-time without needing any specific app and can be accessed from both mobile and desktop.
