### ISSUE TITLE
Research examples of IoT sensors which could be used to detect issues on campus

### ISSUE THREAD

**Issue by TheSloanRanger** [Nintails-TF/agile-smart-campus#19]
As a maintenance staff member, I want IoT sensors integrated into campus facilities to automatically detect and report issues, streamlining maintenance processes and reducing response times.

**Comment by 2418560** [comment]
Building Automation can be used to save money via dynamically adjusting things such as lights, energy draw, avoiding peak load.
It is worth noting that even if it can automatically register issues such as heating not working, regular pre-ventitive maintenance is still valuable for preventing the issues from occuring in the first place.

Here's an example. https://www.aquicore.com/blog/building-automation-system

Low Value: Whilst there is money to be saved in adjusting energy costs, the actual value for the system as it is designed for education is low.

High Risk: An over reliance on this software could cause issues if an issue goes unreported due to a sensor failing.
